services:
  - name: AV-FILE-TO-LINK-PRO
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
    healthCheckPath: "/api/health"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.16"
      - key: PING_INTERVAL
        value: "600"
